name: 2. Generate VPN Subscription
on:
  schedule:
    - cron: '10 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install geoip2 requests
      - name: Download GeoLite2 (Public Mirror)
        run: |
          wget -O GeoLite2-City.mmdb https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-City.mmdb
      - name: Download verified servers
        run: |
          wget -O verified_servers.json "https://raw.githubusercontent.com/ТВОЙ_ЛОГИН/ИМЯ_РЕПОЗИТОРИЯ/main/verified_servers.json"
      - run: python generator.py
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscription.json
          git commit -m "Update subscription $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push